### PR TITLE
feat: use jlink rather than jdk

### PR DESCRIPTION
**Pull request by greut**
It makes the final image smaller.

- 221MB, https://hub.docker.com/layers/prom/cloudwatch-exporter/latest/images/sha256-6a5afd6d7f1cbc90bfea77f0b92942d57422f9a91d441bb293837693a388e867?context=explore
- 71MB, https://hub.docker.com/layers/greut/cloudwatch_exporter/latest/images/sha256-b455dea048b56ad3ce98b2a43669b42a89df9c09aab0099355283d84790180b0?context=explore

### CODE REVIEW

**Comment by matthiasr** [comment]
Interesting, I like the idea especially since it promises reduced memory usage as well. However, I am hesitant to change the Docker image in an incompatible way, especially since I just updated the JDK and base image. What do you think about splitting this out into a separate `-minimal` set of images? Would that be possible in one go or would it require building from scratch twice?

Would it be beneficial to generate a custom launcher script and use it as the entry point, or is that unnecessary?

**Comment by matthiasr** [comment]
Totally fine to keep out of scope, but it slightly bugs me that we are building the exporter twice for amd64 and arm64. Using the same jars in both images would cut down on the build time significantly, especially if that build can happen on the native host architecture.

**Comment by greut** [comment]
All the _magic_ done at the end of the upstream Dockerfile is probably useful as well. https://github.com/docker-library/openjdk/blob/41610205127c2a4f0af64f68b859726993503a89/17/jdk/slim-bullseye/Dockerfile#L67-L86

**Comment by matthiasr** [comment]
@greut do you still want to work on this?

**Comment by greut** [comment]
By splitting that in a separate image, for example?

**Comment by matthiasr** [comment]
Yes!

**Pull request closed without merging**
