### PR TITLE
Auto detect AWS region if none is specified

### LINKED ISSUE #207: Auto detect AWS region
It would be nice to have this feature seeing as prometheus `ec2_sd_configs` allows this. It is ideal for people who want to build a universal AMI that would be run in different AWS accounts/regions without the need to have configuration overrides or hacky solutions.

### PR DESCRIPTION
**Pull request by guidodobboletta**
Fixes #207

### CODE REVIEW

**Comment by brian-brazil** [comment]
The readme needs updating too.

**Comment by guidodobboletta** [comment]
@brian-brazil Updated the readme with the information

**Comment by brian-brazil** [comment]
Thanks!

**Comment by legelstein** [comment]
@brian-brazil any plans for new release after this change?

**Pull request merged**
