### PR TITLE
:sparkles: Enabled backup metrics

### PR DESCRIPTION
**Pull request by afreyermuth98**

### CODE REVIEW

**Comment by afreyermuth98** [comment]
https://github.com/prometheus/cloudwatch_exporter/issues/566

**Comment by matthiasr** [comment]
Can you please add the DCO sign-off? The instructions are in the Details link on the failed check.

**Comment by afreyermuth98** [comment]
Done @matthiasr  :)

**Comment by matthiasr** [comment]
Thank you!

**Pull request merged**
