### PR TITLE
add version, help, and debug flag, debug log GetMetricStatisticsResults

### PR DESCRIPTION
**Pull request by dt-rush**
Change-type: minor
Signed-off-by: dt-rush <nickp@balena.io>

### CODE REVIEW

**Comment by dt-rush** [comment]
Currently testing this in our ec2 instances.

**Comment by brian-brazil** [comment]
I'd prefer not to pull in these dependencies. Logs should already be configurable in the usual fashion.

**Comment by dt-rush** [comment]
@brian-brazil what usual fashion do you indicate?

**Comment by dt-rush** [comment]
I've opened a PR on a branch which has no apache commons CLI dependency here: #222

**Pull request closed without merging**
