### PR TITLE
Add ELB tags to metrics

### PR DESCRIPTION
**Pull request by TomaszSekTesco**
It would be nice to have ELB tags in metrics.

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks for the PR, this has already been discussed in several issues. Adding this for every possible attribute for every possible AWS entity is not sane.

**Comment by antoniaklja** [comment]
@brian-brazil I don't agree. Let assume situation when you have Prometheus+Alertmanager and generic, meanigless ELB metrics attributes. How will you recognize specific ELB for instance in kubernetes cluster?
Lucky guess? don't think so..

**Comment by brian-brazil** [comment]
I don't see what that has to do with my objection.

I'd suggest you look into having more meaningful ELB names.

**Comment by antoniaklja** [comment]
So I'm forced to write my own better implementation. cya

2017-04-25 11:33 GMT+02:00 Brian Brazil <notifications@github.com>:

**Pull request closed without merging**
